version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data
  users-commands:
    volumes:
        - ./monitor_salud/:/mnt/
    build: monitor_salud
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis
  users-queries:
    volumes:
        - ./monitor_salud/:/mnt/
    build: monitor_salud
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on: 
      - redis
  products-commands:
    volumes:
        - ./monitor_ambiente/:/mnt/
    build: monitor_ambiente
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis
  products-queries:
    volumes:
        - ./monitor_ambiente/:/mnt/
    build: monitor_ambiente
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on: 
      - redis
  orders-commands:
    volumes:
        - ./monitor_aperturas/:/mnt/
    build: monitor_aperturas
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on:
      - redis
  orders-queries:
    volumes:
        - ./monitor_aperturas/:/mnt/
    build: monitor_aperturas
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on:
      - redis
  worker-orders:
    volumes:
      - ./monitor_aperturas/:/mnt/
    build: monitor_aperturas
    working_dir: /backend/
    command: rq worker -u 'redis://redis/0'
    depends_on:
      - redis
  worker-products:
    volumes:
      - ./monitor_ambiente/:/mnt/
    build: monitor_ambiente
    working_dir: /backend/
    command: rq worker -u 'redis://redis/1'
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - orders-commands
        - orders-queries
        - users-commands
        - users-queries
        - products-commands
        - products-queries
